INSERT INTO projects (title, category, funding_goal, 'start_date', 'end_date') VALUES ("project1", "beauty", 10000.00, 2018-10-30, 2018-11-30);
INSERT INTO projects (title, category, funding_goal, 'start_date', 'end_date') VALUES ("project1", "beauty", 10000.00, 2018-10-30, 2018-11-30);
INSERT INTO projects (title, category, funding_goal, 'start_date', 'end_date') VALUES ("project1", "beauty", 10000.00, 2018-10-30, 2018-11-30);
INSERT INTO projects (title, category, funding_goal, 'start_date', 'end_date') VALUES ("project1", "beauty", 10000.00, 2018-10-30, 2018-11-30);
INSERT INTO projects (title, category, funding_goal, 'start_date', 'end_date') VALUES ("project1", "beauty", 10000.00, 2018-10-30, 2018-11-30);
INSERT INTO projects (title, category, funding_goal, 'start_date', 'end_date') VALUES ("project1", "beauty", 10000.00, 2018-10-30, 2018-11-30);
INSERT INTO projects (title, category, funding_goal, 'start_date', 'end_date') VALUES ("project1", "beauty", 10000.00, 2018-10-30, 2018-11-30);
INSERT INTO projects (title, category, funding_goal, 'start_date', 'end_date') VALUES ("project1", "beauty", 10000.00, 2018-10-30, 2018-11-30);
INSERT INTO projects (title, category, funding_goal, 'start_date', 'end_date') VALUES ("project1", "beauty", 10000.00, 2018-10-30, 2018-11-30);
INSERT INTO projects (title, category, funding_goal, 'start_date', 'end_date') VALUES ("project1", "beauty", 10000.00, 2018-10-30, 2018-11-30);

INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);
INSERT INTO users ('name', age) VALUES ("hannah", 20);

INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 5, 4);